export const enum MimeType {
  HTML = 'text/html',
  CSS = 'text/css',
  JPEG = 'image/jpeg',
  PNG = 'image/png',
  GIF = 'image/gif',
  MPEG = 'audio/mpeg',
  OGG = 'audio/ogg',
  MP4 = 'video/mp4',
  JSON = 'application/json',
  JAVASCRIPT = 'application/javascript',
  ECMASCRIPT = 'application/ecmascript',
  EXCEL = 'application/vnb.ms-excel',
  CSV = 'application/x-csv',
  ZIP = 'application/zip',
  TGZ = 'application/x-gtar',
  TAR_GZ = 'application/x-gzip',
  XML = 'text/xml',
  TEXT = 'text/plain',
  SVG = 'image/svg+xml',
}
